tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"

#packages
brew "openssl"
brew "node"
brew "npm"
brew "openvpn"
brew "awscli"
brew "tmux"
brew "vim"

cask_args appdir: "/Applications"
cask "anaconda"
cask "firefox"
cask "google-chrome"
cask "dropbox"
cask "skype"
cask "docker"
cask "iterm2"
cask "textmate"
cask "pycharm"
cask "visual-studio-code"
cask "sourcetree"
cask "the-unarchiver"
cask "vlc"
cask "spotify"
cask "sonos"
cask "monolingual"
