tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mutagen-io/mutagen"
brew "augeas"
brew "python@3.9"
brew "awscli"
brew "blueutil"
brew "glib"
brew "cairo"
brew "certbot"
brew "cmake"
brew "cvs"
brew "unbound"
brew "gobject-introspection"
brew "harfbuzz"
brew "leptonica"
brew "libass"
brew "libbluray"
brew "ffmpeg"
brew "fzf"
brew "gdrive"
brew "ghostscript"
brew "gnu-getopt"
brew "go"
brew "gradle"
brew "handbrake"
brew "htop"
brew "jq"
brew "macvim", link: false
brew "mono"
brew "node"
brew "openjdk@11"
brew "openvpn"
brew "python@3.8"
brew "socat"
brew "telnet"
brew "tmux"
brew "typescript"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "mutagen-io/mutagen/mutagen"
cask "anaconda", args: { appdir: "/Applications" }
cask "dropbox", args: { appdir: "/Applications" }
cask "folx"
cask "iterm2", args: { appdir: "/Applications" }
cask "java"
cask "java11"
cask "pycharm", args: { appdir: "/Applications" }
cask "skype", args: { appdir: "/Applications" }
cask "sonos", args: { appdir: "/Applications" }
cask "sourcetree", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "textmate", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "vlc", args: { appdir: "/Applications" }
cask "xquartz"
